name: cv_parser
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - --index-url https://download.pytorch.org/whl/cu128
      - --extra-index-url https://pypi.org/simple
      - torch
      - pandas
      - transformers
      - psycopg2-binary
      - pgvector
      - SQLAlchemy==1.4.54
      - doc2pdf
      - pdfplumber
      - outlines
      - accelerate
      - bitsandbytes
      - vllm
